(setq nano-font-family-monospaced "Droid Sans Mono")
(setq nano-font-family-proportional nil)
(setq nano-font-size 16)

(when (display-graphic-p)
  (+modern-ui-font-h)
  (+modern-ui-chinese-h)
  (+modern-ui-slim-h))

;; Default layout (optional)
(require 'nano-layout)
(require 'nano-base-colors)
(require 'nano-colors)
(require 'nano-theme-light)
;; Theme
(require 'nano-faces)
(nano-faces)
(require 'nano-theme)
(nano-theme)
(require 'nano-modeline)
(require 'nano-compact)
(require 'nano-splash)
(require 'nano-defaults)
(require 'nano-session)
(require 'nano-bindings)
(require 'nano-writer)
(require 'nano-mu4e)
(require 'nano-agenda)
(require 'nano-help)

(provide 'init-nano)
